In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Set a random seed for reproducibility
np.random.seed(42)

In [2]:
# Generate synthetic data
n = 100
x = np.random.normal(5, 5, n)
y = (x > 7).astype(int)

In [3]:
x

array([ 7.48357077,  4.30867849,  8.23844269, 12.61514928,  3.82923313,
        3.82931522, 12.89606408,  8.83717365,  2.65262807,  7.71280022,
        2.68291154,  2.67135123,  6.20981136, -4.56640122, -3.62458916,
        2.18856235, -0.0641556 ,  6.57123666,  0.45987962, -2.06151851,
       12.32824384,  3.8711185 ,  5.33764102, -2.12374093,  2.27808638,
        5.55461295, -0.75496789,  6.87849009,  1.99680655,  3.54153125,
        1.99146694, 14.26139092,  4.93251388, -0.28855464,  9.11272456,
       -1.10421825,  6.04431798, -4.79835062, -1.64093024,  5.98430618,
        8.6923329 ,  5.85684141,  4.42175859,  3.49448152, -2.39260995,
        1.40077896,  2.69680615, 10.28561113,  6.71809145, -3.81520078,
        6.62041985,  3.0745886 ,  1.61539   ,  8.05838144, 10.15499761,
        9.6564006 ,  0.80391238,  3.45393812,  6.65631716,  9.87772564,
        2.60412881,  4.07170512, -0.53167487, -0.98103312,  9.06262911,
       11.78120014,  4.63994939, 10.01766449,  6.80818013,  1.77

In [5]:
y = (x > 7).astype(int)
y

array([1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
(x>7).astype(int)

array([1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# Create a DataFrame
data = pd.DataFrame({'x': x, 'y': y})
data

x  y
0    7.483571  1
1    4.308678  0
2    8.238443  1
3   12.615149  1
4    3.829233  0
..        ... ..
95  -2.317575  0
96   6.480601  0
97   6.305276  0
98   5.025567  0
99   3.827064  0

[100 rows x 2 columns]

In [9]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data[['x']], data['y'], test_size=0.2, random_state=42)

In [10]:
# Logistic Regression
logistic_reg_model = LogisticRegression()
logistic_reg_model.fit(X_train, y_train)
logistic_reg_predictions = logistic_reg_model.predict(X_test)
logistic_reg_accuracy = accuracy_score(y_test, logistic_reg_predictions)

In [11]:
# Compare the models
print(f"Logistic Regression Accuracy: {logistic_reg_accuracy}")

# Predict yi for a new observation xi = 9
new_x = np.array([[9]])
logistic_reg_y_new = logistic_reg_model.predict(new_x)

print(f"Logistic Regression Prediction for xi=9: {logistic_reg_y_new[0]}")

Logistic Regression Accuracy: 0.95
Logistic Regression Prediction for xi=9: 1


/home/sysadm/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [12]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Set a random seed for reproducibility
np.random.seed(42)

# Generate synthetic data
n = 100
x = np.random.normal(5, 5, n)
y = (x > 7).astype(int)

# Create a DataFrame
data = pd.DataFrame({'x': x, 'y': y})

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data[['x']], data['y'], test_size=0.2, random_state=42)

# Logistic Regression
logistic_reg_model = LogisticRegression()
logistic_reg_model.fit(X_train, y_train)
logistic_reg_predictions = logistic_reg_model.predict(X_test)
logistic_reg_accuracy = accuracy_score(y_test, logistic_reg_predictions)

# Compare the models
print(f"Logistic Regression Accuracy: {logistic_reg_accuracy}")

# Predict yi for a new observation xi = 9
new_x = np.array([[9]])
logistic_reg_y_new = logistic_reg_model.predict(new_x)

print(f"Logistic Regression Prediction for xi=9: {logistic_reg_y_new[0]}")


Logistic Regression Accuracy: 0.95
Logistic Regression Prediction for xi=9: 1


/home/sysadm/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [13]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# Set a random seed for reproducibility
np.random.seed(42)

# Generate synthetic data
n = 100
x = np.random.normal(5, 5, n)
y = (x > 7).astype(int)

# Create a DataFrame
data = pd.DataFrame({'x': x, 'y': y})

# Fit a Linear Regression model
X = data[['x']]
y = data['y']

linear_reg_model = LinearRegression()
linear_reg_model.fit(X, y)

# Predict yi for a new observation xi = 9
new_x = np.array([[9]])
linear_reg_y_new = linear_reg_model.predict(new_x)

print(f"Linear Regression Prediction for xi=9: {linear_reg_y_new[0]}")


Linear Regression Prediction for xi=9: 0.5667024749077774


/home/sysadm/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [14]:
# New observation xi = 9
new_x = np.array([[9]])

# Predict yi using the Linear Regression model
linear_reg_y_new = linear_reg_model.predict(new_x)
linear_reg_y_new = 1 if linear_reg_y_new[0] > 0.5 else 0

# Predict yi using the Logistic Regression model
logistic_reg_y_new = logistic_reg_model.predict(new_x)

print(f"Linear Regression Prediction for xi=9: {linear_reg_y_new}")
print(f"Logistic Regression Prediction for xi=9: {logistic_reg_y_new}")


Linear Regression Prediction for xi=9: 1
Logistic Regression Prediction for xi=9: [1]


/home/sysadm/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/home/sysadm/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
